version: '3.1'

services:
  sbcdrink-app:
    container_name: sbcdrink-app
    image: loic08/sbcdrink-app:main
    restart: always
    ports:
      - 3000:3000

  sbcdrink-api:
    image: loic08/sbcdrink-api:main
    container_name: sbcdrink-api
    restart: always
    ports:
      - 8000:8000
    env_file:
      - .env
    networks:
      - sbcdrink-network
    depends_on:
      - sbcdrink-mongo

  sbcdrink-mongo:
    container_name: sbcdrink-mongo
    image: mongo:5.0
    volumes:
      - ./mongo/data:/data/db
      - ./mongo/key:/data/db/key
    healthcheck:
      test: test $$(echo "rs.initiate().ok || rs.status().ok" | mongo -u $${MONGO_INITDB_ROOT_USERNAME} -p $${MONGO_INITDB_ROOT_PASSWORD} --quiet) -eq 1
      interval: 10s
      start_period: 30s
    entrypoint:
      - bash
      - -c
      - |
          echo MYZwB6D3sEG66W5DaYaS > /data/db/key/file.key
          chmod 600 /data/db/key/file.key
          chown 999:999 /data/db/key/file.key
          exec docker-entrypoint.sh $$@
    command: mongod --bind_ip_all --replSet dbrs --keyFile /data/db/key/file.key
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: $DB_USER
      MONGO_INITDB_ROOT_PASSWORD: $DB_PASS
      MONGO_INITDB_DATABASE: $DB_NAME
      MONGO_REPLICA_SET_NAME: rs0
    networks:
      - sbcdrink-network

  sbcdrink-mongo-express:
    container_name: sbcdrink-mongo-express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: $DB_USER
      ME_CONFIG_MONGODB_ADMINPASSWORD: $DB_PASS
      ME_CONFIG_MONGODB_URL: mongodb://$DB_USER:$DB_PASS@sbcdrink-mongo:$DB_PORT/
    networks:
      - sbcdrink-network
    depends_on:
      - sbcdrink-mongo

networks:
  sbcdrink-network:
