# config.yml
belt_engine:
  pin_out_1: 10
  pin_out_2: 25
  pin_out_3: 9
  pin_out_4: 11
  step_sleep: 0.0025
bottle_engine:
  pin_out_1: 17
  pin_out_2: 18
  pin_out_3: 27
  pin_out_4: 22
  step_sleep: 0.001
belt_limit_sensor:
  pin_signal: 16
present_position: 1700
